services:
  db:
    image: postgres:latest
    container_name: hubdb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pachkahleba42
      POSTGRES_DB: hubdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
volumes:
  db-data: