// <auto-generated />
using System;
using HubbersApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HubbersApp.Infrastructure.Migrations
{
    [DbContext(typeof(HubDbContext))]
    partial class HubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HubbersApp.Infrastructure.Models.Hubber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Hub Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Hub Member Name");

                    b.HasKey("Id");

                    b.ToTable("Hubbers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cfa5267c-769b-4faa-8680-b49b6d1de959"),
                            Name = "Hubber 1"
                        },
                        new
                        {
                            Id = new Guid("64b84d3c-946c-46e7-a9df-9e3f3123c8cb"),
                            Name = "Hubber 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
